// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8geh7n6lz1sh5acxlJWh33-in8c5uo9g',
    appId: '1:716116140279:web:25ebaf6248a54adb4ef3f2',
    messagingSenderId: '716116140279',
    projectId: 'nifty-ba510',
    authDomain: 'nifty-ba510.firebaseapp.com',
    storageBucket: 'nifty-ba510.appspot.com',
    measurementId: 'G-K45WL4S1SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWktZityxvNLdneUOeFC7L8ozD05kja7Y',
    appId: '1:716116140279:android:0a3fed41f3a7f4794ef3f2',
    messagingSenderId: '716116140279',
    projectId: 'nifty-ba510',
    storageBucket: 'nifty-ba510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1UvQcOzSI-9ot5C86bEJuYcw5mzdOaPY',
    appId: '1:716116140279:ios:146fd8a963702ead4ef3f2',
    messagingSenderId: '716116140279',
    projectId: 'nifty-ba510',
    storageBucket: 'nifty-ba510.appspot.com',
    iosClientId: '716116140279-k8pmsm7t4p1eqmkb3bcs5mv87264776q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nifty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1UvQcOzSI-9ot5C86bEJuYcw5mzdOaPY',
    appId: '1:716116140279:ios:146fd8a963702ead4ef3f2',
    messagingSenderId: '716116140279',
    projectId: 'nifty-ba510',
    storageBucket: 'nifty-ba510.appspot.com',
    iosClientId: '716116140279-k8pmsm7t4p1eqmkb3bcs5mv87264776q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nifty',
  );
}
